source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNSprite_Example', :exclusive => true do
  pod "NNSprite", :path => "../"
end

target 'NNSprite_Tests', :exclusive => true do
  pod "NNSprite", :path => "../"

  
end
